const nodemailer = require('nodemailer');
const path = require('path');

/**
 * Email Service - Sends survey PDF via Gmail SMTP using Nodemailer.
 * 
 * The receiver email is configured only on the backend via environment variables.
 * It is never exposed to the frontend or the user.
 */

/**
 * Create a Nodemailer transporter using Gmail SMTP
 */
const createTransporter = () => {
  return nodemailer.createTransport({
    service: process.env.SMTP_SERVICE || 'gmail',
    auth: {
      user: process.env.SMTP_EMAIL,
      pass: process.env.SMTP_APP_PASSWORD,
    },
  });
};

/**
 * Send the survey PDF via email
 * 
 * @param {string} trackingCode - The unique tracking code
 * @param {string} pdfPath - The file path to the generated PDF
 * @returns {Promise<Object>} - The email send result
 */
const sendSurveyEmail = async (trackingCode, pdfPath) => {
  const transporter = createTransporter();

  const submittedDate = new Date().toLocaleDateString('en-ZA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  // Support multiple recipients by splitting comma-separated emails
  const recipients = process.env.RECEIVER_EMAILS
    ? process.env.RECEIVER_EMAILS.split(',').map(email => email.trim())
    : process.env.RECEIVER_EMAIL;

  const mailOptions = {
    from: process.env.SMTP_EMAIL,
    to: recipients,
    subject: `New Customer Satisfaction Survey - Tracking Code: ${trackingCode}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
        <div style="background-color: #b30015; padding: 15px; border-radius: 5px 5px 0 0; margin: -20px -20px 20px -20px;">
          <h2 style="color: #ffffff; margin: 0; font-size: 18px;">CNG Customer Satisfaction Survey</h2>
        </div>
        
        <p style="font-size: 14px; color: #333;">A new Customer Satisfaction Survey has been submitted.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
          <tr>
            <td style="padding: 8px; background-color: #f5f5f5; font-weight: bold; width: 150px;">Tracking Code:</td>
            <td style="padding: 8px; background-color: #f5f5f5;">${trackingCode}</td>
          </tr>
          <tr>
            <td style="padding: 8px; font-weight: bold;">Submission Date:</td>
            <td style="padding: 8px;">${submittedDate}</td>
          </tr>
        </table>
        
        <p style="font-size: 14px; color: #333;">The completed survey PDF is attached to this email.</p>
        
        <div style="background-color: #fdf3f4; padding: 10px; border-left: 4px solid #b30015; margin: 15px 0; font-size: 12px; color: #666;">
          <p style="margin: 0;">This is an automated email from the CNG Customer Satisfaction Survey system.</p>
          <p style="margin: 5px 0 0 0;">Generated by SmartMat Technologies Pty Ltd</p>
        </div>
      </div>
    `,
    attachments: [
      {
        filename: path.basename(pdfPath),
        path: pdfPath,
      },
    ],
  };

  const info = await transporter.sendMail(mailOptions);
  console.log(`Email sent successfully: ${info.messageId}`);
  return info;
};

module.exports = { sendSurveyEmail };