const fs = require('fs/promises');
const path = require('path');

const EMAIL_PROVIDER = 'resend';
const RECEIVER_EMAILS = process.env.RECEIVER_EMAILS || process.env.RECEIVER_EMAIL;
const RESEND_API_KEY = process.env.RESEND_API_KEY;
const RESEND_FROM = process.env.RESEND_FROM || 'onboarding@resend.dev';
const RESEND_TEST_RECIPIENT = process.env.RESEND_TEST_RECIPIENT || 'sbongilesedibe@gmail.com';

const getRecipients = () => {
  const rawRecipients = RECEIVER_EMAILS || '';
  const recipients = rawRecipients
    .split(',')
    .map((email) => email.trim())
    .filter(Boolean);

  if (recipients.length === 0) {
    return [RESEND_TEST_RECIPIENT];
  }

  return recipients;
};

const logEmailConfig = () => {
  console.log(`[EMAIL] Provider: ${EMAIL_PROVIDER}`);
  console.log(`[EMAIL] RESEND_API_KEY: ${RESEND_API_KEY ? 'configured' : 'missing'}`);
  console.log(`[EMAIL] RESEND_FROM: ${RESEND_FROM || 'missing'}`);
  console.log(`[EMAIL] RECEIVER_EMAILS: ${RECEIVER_EMAILS ? 'configured' : 'missing'}`);
};

const validateEmailConfig = () => {
  logEmailConfig();

  if (!RESEND_API_KEY) {
    throw new Error('Missing Resend API key. Set RESEND_API_KEY in the server environment.');
  }

  getRecipients();
};

const classifyEmailError = (error) => {
  const status = error && error.status;
  const message = error && error.message ? error.message : 'Unknown email error';

  if (status === 401) {
    return 'Resend authentication failed. Check RESEND_API_KEY.';
  }

  if (status === 422) {
    return 'Resend rejected the request. Verify your domain in Resend and use a sender email from that verified domain.';
  }

  return `Email failed: ${message}`;
};

const verifyEmailConnection = async () => {
  console.log('[EMAIL] Starting Resend configuration verification...');
  validateEmailConfig();
  console.log('[EMAIL] Resend configuration verified successfully.');
  return true;
};

const buildEmailContent = (trackingCode, pdfPath) => {
  const recipients = getRecipients();
  const submittedDate = new Date().toLocaleDateString('en-ZA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  console.log(`[EMAIL] Preparing message for ${recipients.length} recipient(s). Attachment=${path.basename(pdfPath)}`);

  return {
    from: RESEND_FROM,
    to: recipients,
    subject: `New Customer Satisfaction Survey - Tracking Code: ${trackingCode}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
        <div style="background-color: #b30015; padding: 15px; border-radius: 5px 5px 0 0; margin: -20px -20px 20px -20px;">
          <h2 style="color: #ffffff; margin: 0; font-size: 18px;">CNG Customer Satisfaction Survey</h2>
        </div>
        <p style="font-size: 14px; color: #333;">A new Customer Satisfaction Survey has been submitted.</p>
        <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
          <tr>
            <td style="padding: 8px; background-color: #f5f5f5; font-weight: bold; width: 150px;">Tracking Code:</td>
            <td style="padding: 8px; background-color: #f5f5f5;">${trackingCode}</td>
          </tr>
          <tr>
            <td style="padding: 8px; font-weight: bold;">Submission Date:</td>
            <td style="padding: 8px;">${submittedDate}</td>
          </tr>
        </table>
        <p style="font-size: 14px; color: #333;">The completed survey PDF is attached to this email.</p>
        <div style="background-color: #fdf3f4; padding: 10px; border-left: 4px solid #b30015; margin: 15px 0; font-size: 12px; color: #666;">
          <p style="margin: 0;">This is an automated email from the CNG Customer Satisfaction Survey system.</p>
          <p style="margin: 5px 0 0 0;">Generated by SmartMat Technologies Pty Ltd</p>
        </div>
      </div>
    `,
  };
};

const sendViaResend = async (trackingCode, pdfPath) => {
  const emailContent = buildEmailContent(trackingCode, pdfPath);
  const pdfBuffer = await fs.readFile(pdfPath);

  const payload = {
    from: emailContent.from,
    to: emailContent.to,
    subject: emailContent.subject,
    html: emailContent.html,
    attachments: [
      {
        filename: path.basename(pdfPath),
        content: pdfBuffer.toString('base64'),
        contentType: 'application/pdf',
      },
    ],
  };

  console.log('[EMAIL] Resend payload:', JSON.stringify(payload));

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  const data = await response.json().catch(() => ({}));

  if (!response.ok) {
    const error = new Error(data.message || `Resend request failed with status ${response.status}`);
    error.status = response.status;
    throw error;
  }

  console.log(`[EMAIL] Resend email sent successfully. Id=${data.id}`);
  return data;
};

const sendSurveyEmail = async (trackingCode, pdfPath) => {
  validateEmailConfig();
  return sendViaResend(trackingCode, pdfPath);
};

module.exports = {
  sendSurveyEmail,
  verifyEmailConnection,
  classifyEmailError,
};

